# Generated by Django 4.0.8 on 2022-12-14 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('productos', '0003_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria2',
            field=models.ManyToManyField(to='categorias.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='categorias.categoria'),
        ),
    ]
